# Generated by Django 4.2 on 2023-05-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'Учетная запись пользователя', 'verbose_name_plural': 'Учетные записи пользователей'},
        ),
    ]
