# Generated by Django 4.2 on 2023-04-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_alter_cart_options_category_targeted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
