# Generated by Django 4.2 on 2023-06-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
    ]
