# Generated by Django 4.2 on 2023-04-14 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
    ]
