# Generated by Django 4.2 on 2023-04-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='img',
            field=models.ImageField(upload_to='assets/partners/', verbose_name='Логотип'),
        ),
    ]
