# Generated by Django 4.2 on 2023-05-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0009_alter_partner_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Логотип'),
        ),
    ]
